plugins:
- jekyll-seo-tag
- jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
# Name of website
title: My website

# Your name to show in the footer
author: Some Person





<!-- theme: jekyll-theme-cayman --> 
