plugins:
- jekyll-seo-tag
- jekyll-relative-links
relative_links:
  enabled: true
  collections: true
navbar-links:
  About Me: "aboutme"
  Resources:
    - X6100 gists: "https://gist.github.com/search?q=user%3Adjbr1+x6100"
    - Load Sensor Keyer: "https://github.com/djbr1/k3ng_cw_keyer/blob/master/k3ng_keyer/ADC_CS1237/README.md"
  Author's home: "https://www.qrz.com/db/hb9txb"
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
# Name of website
title: <!-- Branko Djokic HB9TXB -->
description: "Electronic Keyer with Integrated Load Sensor Paddles"
tags:
  - load sensor
  - weight sensor
  - load cell
  - cw keyer
  - electronic keyer
  - iambic keyer
  - CS1237
  - arduino
  - paddles
  - strain gauge
  - ham radio
  - amateur radio
  - morse
  

# Your name to show in the footer
author:  
   name: Branko Djokic HB9TXB
   email: bdjokic@bluewin.ch
   home: https://www.qrz.com/db/hb9txb
   




<!-- theme: jekyll-theme-minimal -->
